module.exports = {
  messages: [
    "Reticulating splines...",
    "Generating witty dialog...",
    "Swapping time and space...",
    "Spinning violently around the y-axis...",
    "Tokenizing real life...",
    "Bending the spoon...",
    "Filtering morale...",
    "We need a new fuse...",
    "The architects are still drafting...",
    "Breeding the bits...",
    "We're building the buildings as fast as we can",
    "Enjoying the elevator music...",
    "Checking the gravitational constant in your locale...",
    "Reconfoobling energymotron...",
    "Counting backwards from Infinity...",
    "Don't panic...",
    "Embiggening Prototypes...",
    "Spinning the wheel of fortune...",
    "Loading the enchanted bunny...",
    "Computing chance of success...",
    "Adjusting flux capacitor...",
    "Keeping all the 1's and removing all the 0's...",
    "Cleaning off the cobwebs...",
    "Making sure all the i's have dots...",
    "Connecting Neurotoxin Storage Tank...",
    "Convincing AI not to turn evil...",
    "Computing the secret to life, the universe, and everything...",
    "Constructing additional pylons...",
    "Roping a couple of sea turtles...",
    "Dividing by zero...",
    "Spawning the Overlord...",
    "Cracking military-grade encryption...",
    "Simulating traveling salesman...",
    "Proving P=NP...",
    "Entangling superstrings...",
    "Searching for plot device...",
    "Trying to sort in O(n)...",
    "Looking for sense of humour...",
    "Ordering 1s and 0s...",
    "Updating dependencies...",
    "Whatever you do, don't look behind you...",
    "Consulting the manual...",
  ],

  generateFunnies: function() {
    return module.exports.messages[Math.floor(Math.random() * module.exports.messages.length)];
  }

};
